name: Photogram
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: echo "I am from Photogram App"
      - run: echo "Deployed!"
