name: Photogram Developement Server
run-name: ${{ github.actor }} is Developing a Photogram App.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"
      - run: ls
      - run: pwd
      - run: whoami
