name: Photogram
run-name: Photogram Dev WorkFlow
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: echo "I am from Photogram App"
      - run: sudo rm -rf /home/mspraveenkumar77/htdocs/photogram
      - run: sudo cp -r $(pwd) /home/mspraveenkumar77/htdocs/photogram
      - run: sudo rm -rf /home/mspraveenkumar77/htdocs/photogram/.git
      - run: sudo rm -rf /home/mspraveenkumar77/htdocs/photogram/.github/
      - run: pwd
      - run: echo "Job Finished"
      - run: echo "Deployed!"
