name: Photogram
run-name: Photogram Dev WorkFlow
on: [push]
jobs:
  check-bats-version:
    runs-on: self-hosted
    steps:
      - run: pwd
      - run: echo "I am from Photogram App"
      - run: echo "Deployed!"
